export enum GameStatus {
    STARTED = 'STARTED',
    GUESSING = 'GUESSING',
    LAST_NUMBER_BIGGER = 'LAST_NUMBER_BIGGER',
    LAST_NUMBER_LOWER = 'LAST_NUMBER_LOWER',
    GAME_WON = 'GAME_WON',
    STANDBY = 'STANDBY'
}